#!/bin/bash

# 将新的文献总结与翻译 md 文档 push 至远程 git 仓库

refs_md_path="${HOME}/scripts/Codex-Papers-Summary"
if [[ $HOSTNAME =~ "DESKTOP" ]]; then
  refs_md_path="/mnt/e/Codex-Papers-Summary"
elif [[ $HOSTNAME =~ "LAPTOP" ]]; then
  refs_md_path="/mnt/d/Codex-Papers-Summary"
fi

git_update() {
  BRANCH=$(git branch --show-current)
  git status --short --branch
  echo
  git add .
  git commit -m "add md files"
  echo
  git push origin "${BRANCH}"
}

update_num() {
  cd "${refs_md_path}" || exit

  update_md_num=$(git status --short -z | grep -zc "\.md$")

  if [[ $update_md_num -eq 0 ]]; then
    echo -e "\nNo md files to add.\n"
  else
    echo -e "\n${update_md_num} md file(s) is(are) added.\n"
    git_update
  fi

  cd - >/dev/null 2>&1 || exit
}

update_num
